### PR TITLE
removed uppercase from state on shops and producers lists in the frontoffice

### PR DESCRIPTION
**Pull request by luisramos0**
to be added to https://github.com/openfoodfoundation/openfoodnetwork/pull/1969

### CODE REVIEW

**Comment by sauloperez** [comment]
Hey @luisramos0 this should rather point to openfoodfoundation's OFN repo. This is just the fork where some of us work from.

**Comment by luisramos0** [comment]
Hi Pau, ok. I think I need a little github workflow guidance here.
If this is not the best option and I don't think I have access to commit on top of the existing PR on OFN (1969), I see two other options:
A- create a new PR on OFN with all the changes (including the changes on PR 1969)
B- create a new PR on OFN with only my changes (incremental to what's on PR 1969)
Thanks for your help!
Luís

**Comment by sauloperez** [comment]
I would go with option B clearly stating in the description the dependency on the PR 1969. https://help.github.com/articles/fork-a-repo/ might be of help.

**Comment by luisramos0** [comment]
ok, awesome, thanks for the link, I have  my own fork of ofn. I was just not sure what type of PR was needed in this case.
Ill go for option B.
Thanks!

**Comment by mkllnk** [comment]
Good call. It depends on the nature of the change. I would consider your pull request as independent and it should be opened towards openfoodfoundation master, just with your change.

But if you can't separate your commits from another pull request easily, you can also open a competing pull request. We then close the old one and merge the new one.

**Comment by luisramos0** [comment]
ok guys, thanks for the guidance!
I opened
https://github.com/openfoodfoundation/openfoodnetwork/pull/2345
to complement the original PR from Maxim https://github.com/openfoodfoundation/openfoodnetwork/pull/1969

**Comment by enricostano** [comment]
Can we close this PR?

**Comment by luisramos0** [comment]
Hi, I think you can, it has been merged to ofn. Thanks!

**Pull request closed without merging**
